# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='hotel_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
